// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcP8W-40YyGD2-iks5bT1CNkG6iN9ogY8',
    appId: '1:154893702920:web:1d75df2b5e85e634a8bebd',
    messagingSenderId: '154893702920',
    projectId: 'mytask-e91e3',
    authDomain: 'mytask-e91e3.firebaseapp.com',
    storageBucket: 'mytask-e91e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtaAfYCjJwo3DXLXpliozFHkOag968Ks8',
    appId: '1:154893702920:android:a48a20e3eeb42ebca8bebd',
    messagingSenderId: '154893702920',
    projectId: 'mytask-e91e3',
    storageBucket: 'mytask-e91e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5XBew-8XdQGYhcJRf_qR2c_WJIpFq9dc',
    appId: '1:154893702920:ios:1d20f5c1621e8eaea8bebd',
    messagingSenderId: '154893702920',
    projectId: 'mytask-e91e3',
    storageBucket: 'mytask-e91e3.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5XBew-8XdQGYhcJRf_qR2c_WJIpFq9dc',
    appId: '1:154893702920:ios:1d20f5c1621e8eaea8bebd',
    messagingSenderId: '154893702920',
    projectId: 'mytask-e91e3',
    storageBucket: 'mytask-e91e3.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcP8W-40YyGD2-iks5bT1CNkG6iN9ogY8',
    appId: '1:154893702920:web:055801624f5ffb0aa8bebd',
    messagingSenderId: '154893702920',
    projectId: 'mytask-e91e3',
    authDomain: 'mytask-e91e3.firebaseapp.com',
    storageBucket: 'mytask-e91e3.firebasestorage.app',
  );
}
